import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { useI18n } from '../hooks/useI18n';
import LanguageSelector from './LanguageSelector';
const LanguageDemo = () => {
    const { t, i18n } = useI18n();
    const currentLanguage = i18n.language;
    return (_jsxs("div", { className: "max-w-4xl mx-auto p-6 space-y-8", children: [_jsxs("div", { className: "text-center", children: [_jsx("h1", { className: "text-3xl font-bold text-gray-900 mb-4", children: t('languageDemo.title') }), _jsx("p", { className: "text-gray-600 mb-6", children: t('languageDemo.description') })] }), _jsxs("div", { className: "bg-white rounded-lg shadow-md p-6", children: [_jsx("h2", { className: "text-xl font-semibold mb-4", children: t('languageDemo.currentLanguage') }), _jsx("p", { className: "text-lg", children: _jsx("span", { className: "font-medium", children: currentLanguage }) })] }), _jsxs("div", { className: "bg-white rounded-lg shadow-md p-6", children: [_jsx("h2", { className: "text-xl font-semibold mb-4", children: t('languageDemo.selectYourLanguage') }), _jsx(LanguageSelector, {})] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsxs("div", { className: "bg-white rounded-lg shadow-md p-6", children: [_jsx("h3", { className: "text-lg font-semibold mb-4", children: t('languageDemo.greeting') }), _jsx("p", { className: "text-gray-700", children: t('languageDemo.greeting', { name: 'João', count: 5 }) })] }), _jsxs("div", { className: "bg-white rounded-lg shadow-md p-6", children: [_jsx("h3", { className: "text-lg font-semibold mb-4", children: t('languageDemo.plural.message_one') }), _jsx("p", { className: "text-gray-700", children: t('languageDemo.plural.message_one', { count: 1 }) }), _jsx("p", { className: "text-gray-700 mt-2", children: t('languageDemo.plural.message_other', { count: 10 }) })] })] }), _jsxs("div", { className: "bg-white rounded-lg shadow-md p-6", children: [_jsx("h3", { className: "text-lg font-semibold mb-4", children: t('languageDemo.interpolationExample') }), _jsx("p", { className: "text-gray-700", children: t('languageDemo.interpolationExample', {
                            user: 'Maria',
                            date: new Date().toLocaleDateString()
                        }) })] }), _jsxs("div", { className: "bg-white rounded-lg shadow-md p-6", children: [_jsx("h3", { className: "text-lg font-semibold mb-4", children: t('languageDemo.dynamicContent') }), _jsxs("div", { className: "space-y-2", children: [_jsx("p", { className: "text-gray-700", children: t('languageDemo.itemCount', { count: 1 }) }), _jsx("p", { className: "text-gray-700", children: t('languageDemo.itemCount_plural', { count: 5 }) }), _jsx("p", { className: "text-gray-700", children: t('languageDemo.dateExample', { date: new Date().toLocaleDateString() }) }), _jsx("p", { className: "text-gray-700", children: t('languageDemo.currencyExample', { price: '$99.99' }) }), _jsx("p", { className: "text-gray-700", children: t('languageDemo.numberExample', { number: 12345 }) })] })] }), _jsxs("div", { className: "bg-white rounded-lg shadow-md p-6", children: [_jsx("h3", { className: "text-lg font-semibold mb-4", children: t('languageDemo.nestedTranslation') }), _jsx("p", { className: "text-gray-700", children: t('languageDemo.nestedTranslation', {
                            nested: t('languageDemo.nestedValue')
                        }) })] }), _jsxs("div", { className: "bg-white rounded-lg shadow-md p-6", children: [_jsx("h3", { className: "text-lg font-semibold mb-4", children: t('languageDemo.complexExample') }), _jsx("p", { className: "text-gray-700", children: t('languageDemo.complexExample', {
                            val: 'primeiro valor',
                            anotherVal: 'segundo valor'
                        }) })] }), _jsx("div", { className: "text-center", children: _jsx("button", { className: "bg-blue-600 text-white px-6 py-3 rounded-lg hover:bg-blue-700 transition-colors", children: t('languageDemo.buttonText') }) }), _jsx("div", { className: "text-center text-gray-500 text-sm", children: _jsx("p", { children: t('languageDemo.footerText') }) })] }));
};
export default LanguageDemo;
